.TH "ALSA-MIDI-LATENCY-TEST" "1" "0.0.4" "01/2014" ""
.SH NAME
alsa-midi-latency-test \- measures latency of a MIDI loop back chain.

.SH SYNOPSIS
.B alsa-midi-latency-test
\-o client:port -i client:port [options]
.br
.B alsa-midi-latency-test
\-\-help

.SH DESCRIPTION
.B alsa-midi-latency-test
measures latency of a MIDI device or a MIDI loop back chain.

To interrupt a running latency measurement test, press <Ctrl+C>.

.SH OPTIONS

.TP
.I \-o,\-\-output=client:port
Sets the sequencer output port where test events are sent to.

A client can be specified by its number, its name, or a prefix of its
name. A port is specified by its number; for port 0 of a client, the
":0" part of the port specification can be omitted.

.TP
.I \-i,\-\-input=client:port
Sets the sequencer input port where test events are received from.

A client can be specified by its number, its name, or a prefix of its
name. A port is specified by its number; for port 0 of a client, the
":0" part of the port specification can be omitted.

.TP
.I \-l,\-\-list
Lists MIDI input and output ports.

.TP
.I \-R,\-\-realtime
Enables realtime scheduling priorization. (default: no rt).

.TP
.I \-P,\-\-priority=int
When running with --realtime, sets the scheduler priority to int.

.TP
.I \-S,\-\-samples=int
Sets the given number of samples (default: 10000) to take.

.TP
.I \-s,\-\-skip=int
Skip measuring latency for the given number of samples (default: 0/no sample skip).

.TP
.I \-w,\-\-wait=ms
Wait ms milliseconds between measurements (default: 0ms).

.TP
.I \-r,\-\-random-wait
Wait between wait and 2*wait milliseconds between measurements (default: off/no wait).

.TP
.I \-h,\-\-help
Prints a list of options.

.TP
.I \-V,\-\-version
Prints the current version.

.SH SEE ALSO
.PP
.I https://www.linuxaudio.org/resources.html
.br
The linux-audio tuning (LAT) mailing list is to help GNU/Linux distribution
maintainers and other interested users to share information on system
performance tuning matters, especially with regard to real-time Linux
kernels.
.PP
.I http://www.alsa\-project.org
.br
The Advanced Linux Sound Architecture.

.SH BUGS
Please report bugs to the authors.

.SH AUTHORS
Jakob Flierl <jakob.flierl@gmail.com>
