on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install devscripts
      run: sudo apt -y install devscripts equivs
    - name: install build dependencies
      run: sudo mk-build-deps --install debian/control
    - name: build the package
      run: dpkg-buildpackage -b -rfakeroot -us -uc
    - name: install the package
      run: sudo dpkg -i ../alsa-midi-latency-test*deb
    - name: install package dependencies
      run: sudo apt -f install
